.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

======================================================================
                            studio_snatch
======================================================================
----------------------------------------------------------------------
              Exhaustive SUSE Studio API validation tool
----------------------------------------------------------------------

:Author: Roman Neuhauser
:Contact: rneuhauser@suse.cz
:Copyright: This document is in the public domain.

Usage
=====

::

  git init somedir
  cd somedir
  git remote add upstream -t master -m master \
    https://github.com/roman-neuhauser/studio_snatch.git
  git fetch upstream
  git checkout -t upstream/master
  make
  ./bin/ssnatch http://apiuser:apikey@machine[:port]

